language: php
php:
  - 7.0
  - 7.1
  - 7.2

env:
  matrix:
    - laravel=5.8.x
    - laravel=5.7.x
    - laravel=5.6.x
    - laravel=5.5.x
    - laravel=5.4.x

matrix:
  include:
    - php: 5.6
      env: laravel=default
  exclude:
    - php: 7.0
      env: laravel=5.6.x
    - php: 7.0
      env: laravel=5.7.x
    - php: 7.0
      env: laravel=5.8.x

cache:
  directories:
    - $HOME/.composer/cache

sudo: false

before_install:
  - phpenv config-rm xdebug.ini

install:
  - if [ $laravel != 'default' ]; then travis_retry composer require illuminate/support:${laravel} --no-update --no-interaction; fi
  - travis_retry composer install --prefer-dist --no-interaction --no-suggest

script: vendor/bin/phpunit --verbose
