language: php
php:
  - 5.6
  - 7.0
  - 7.1

env:
  global:
    - laravel=5.x

matrix:
  include:
    - php: 5.6
      env: laravel=5.3.x
    - php: 7.0
      env: laravel=5.5.x

cache:
  directories:
    - $HOME/.composer/cache

sudo: false

before_install:
  - phpenv config-rm xdebug.ini
  - travis_retry composer self-update

install:
  - travis_retry composer require illuminate/support:${laravel} --no-update --no-interaction --no-suggest
  - travis_retry composer install --prefer-dist --no-interaction --no-suggest

script: vendor/bin/phpunit --verbose
