language: php
php:
  - 7.0
  - 7.1
  - 7.2

env:
  matrix:
    - laravel=5.5.x
    - laravel=5.4.x

matrix:
  include:
    - php: 5.6
      env: laravel=5.4.x

cache:
  directories:
    - $HOME/.composer/cache

sudo: false

before_install:
  - phpenv config-rm xdebug.ini
  - travis_retry composer self-update

install:
  - travis_retry composer require illuminate/support:${laravel} --no-update --no-interaction
  - travis_retry composer install --prefer-dist --no-interaction --no-suggest

script: vendor/bin/phpunit --verbose
